---
- name: Install python
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install python2
      raw: test -e /usr/bin/python || (apt update && apt install -y python-minimal)
      changed_when: false
