---
- name: Deploy app
  hosts: app
  vars:
    deploy_user: appuser
  tasks:
  - name: Fetch latest version of app
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/{{ deploy_user }}/reddit
      version: monolith
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/{{ deploy_user }}/reddit
    notify: restart puma
  
  handlers:
  - name: restart puma
    become: yes
    systemd:
      name: puma
      state: restarted
