- name: Configure app host
  hosts: app
  become: true
  tags: app-tag
  vars:
    db_host: 1.1.1.1
  tasks:
    - name: Install puma service
      become: true
      ansible.builtin.copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
    - name: reload-daemons
      become: true
      ansible.builtin.shell:
        cmd: systemctl daemon-reload
    - name: Add config for DB connection
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
      notify:
      - restart puma
    - name: enable puma.service
      become: true
      ansible.builtin.systemd:
        name: puma
        enabled: true
      notify:
      - restart puma
  handlers:
    - name: restart puma
      become: true
      ansible.builtin.systemd:
        name: puma
        state: restarted
