---
- name: Deploy app
  hosts: app
  tags: deploy-tag
  tasks:
  - name: Fetch latest version of app
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
