---
- name: Configure db
  hosts: db
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tags: db-tag
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      notify:
      - restart mongodb
  handlers:
    - name: restart mongodb
      become: true
      service:
        name: mongodb
        state: restarted

- name: Configure app host
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 158.160.114.207
  tasks:
    - name: Install puma service
      become: true
      copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
    - name: reload-daemons
      become: true
      shell:
        cmd: systemctl daemon-reload
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
    - name: enable puma.service
      become: true
      systemd:
        name: puma
        enabled: true
      tags: app-tag
      notify:
      - restart puma
  handlers:
    - name: restart puma
      become: true
      systemd:
        name: puma
        state: restarted
- name: Deploy application
  hosts: app
  tags: deploy-tag
  tasks:
  - name: Fetch latest version of app
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
    notify: restart puma
  handlers:
    - name: restart puma
      become: true
      systemd:
        name: puma
        state: restarted
