---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 158.160.101.255
  tasks:

    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      tags: db-tag
      notify:
      - restart mongodb

    - name: Fetch latest version of app
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag
    - name: Install puma service
      become: true
      copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag

    - name: reload-daemons
      become: true
      shell:
        cmd: systemctl daemon-reload
      tags: app-tag
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag

    - name: enable puma.service
      become: true
      systemd:
        name: puma
        enabled: true
      tags: app-tag
      notify:
      - restart puma

  handlers:
    - name: restart mongodb
      become: true
      service:
        name: mongodb
        state: restarted
    - name: restart puma
      become: true
      systemd:
        name: puma
        state: restarted
